### ISSUE TITLE
analyse changes needed to update gui 

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#23]

**Comment by eltonnuness** [comment]
Steve,

I analyse the project

To update the gui maybe we can use the JavaFX, and to make this, We need create the windows with Scene Builder, and make a new classes in package gui.generated.

**Comment by leonarduk** [comment]
How long long do you think it might take?

**Comment by eltonnuness** [comment]
I do not know if you already worked with JavaFX but to create the windows of application is very fast with Scene Builder. The challenge is create a new controller and all calls of the program with threads and integrate some tools. I already create simple application in JavaFX,such did you see. I never created an complete application. Really do not know how much time I need to create it, because I do not know how your program works completely.

I can create the windows of application and I try call some functions, maybe this can help by for now.

**Comment by leonarduk** [comment]
Closing this as its covered by the other issues
