### ISSUE TITLE
improve test coverage 

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#5]
Currently only 2%!

**Comment by leonarduk** [comment]
I have integrated this with a tool that shows test coverage

https://codecov.io/gh/leonarduk/unison/tree/88797d1909ad681011be8beb4b47b7ec592ef23f/src/main/java/uk/co/sleonard/unison

**Comment by eltonnuness** [comment]
Oh Very interesting

**Comment by leonarduk** [comment]
Hi,  I moved the tests out of the .tests subfolders and excluded the gui projects.  Total coverage is now much better.  We still need to improve it though.

Could you list which classes you find hard to test here please?

**Comment by eltonnuness** [comment]
Ok, I will verify which

**Comment by eltonnuness** [comment]
.../input
**DataHibernatorWorker** - UNIsonController.getInstance.helper, this causing errors sometimes
**FullDownloadWorker** - downloadQueue.poll() this causing nullpointer.
**HeaderDownloadWorker** - for example - method queueMessages use the UNISONController.getInstance().getQueue() - this cause null pointer because getQueue, the class need refactor on constructor to receive the Unisoncontroller to we can mock this?
**LocationFinder** - I am doubt because apparently only have integration tests, and you make this in /it/java, I can not see how create unit test in this class.
**NewsClient** - apparently only have also integration tests. I can not see how create unit test here. Once the class make the connection with server.

.../output
**ExportToCSV** - I got create some tests but have the Method exportTableToCSV that open a gui, how test this ?

If you no understand something, ask to me.

Thank you for support Steve.

**Comment by leonarduk** [comment]
I have created new issue #89 for me to do

**Comment by leonarduk** [comment]
I have excluded gui projects from coverage and refactored to leave the non gui bits out of gui. Coverage is now at 50% but we should be able to add more tests

**Comment by leonarduk** [comment]
I think we need 80% coverage. May settle for 70% for this task.

**Comment by eltonnuness** [comment]
YEs

**Comment by leonarduk** [comment]
above 70%
