### ISSUE TITLE
remove third party code from codebase 

### ISSUE THREAD

**Issue by leonarduk** [leonarduk/unison#56]
Want to remove the Apache code and use a jar from maven instead

**Comment by leonarduk** [comment]
Do you want to take a look at this? The agile way would be to move the test coverage task back to todo and put this in progress so you only have one in progress at a time

**Comment by eltonnuness** [comment]
Ok, I take a look at this

**Comment by eltonnuness** [comment]
#57 COMMIT

I deleted all classes commons.net, and update the maven commons.net library to 3.5(last version). 

But It Occurred code break in NewsClient.java connect() method, because of UniSoNException no is applicable on SuperClass SocketClient, I think you needed add on the method to throws Exception when in development to permit you can throws your custom exception

I tried make a adjust in exceptions, now the program run normally.

Please, see my changes on NewsClient and FullDownloadWorker to verify if my changes no cause trouble in catch exceptions.
